name: Update Azure VM passwords
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * 1' ##Runs at 9AM UTC every Monday##

permissions:
  id-token: write
  contents: read

jobs:
  rotatePwd:
    runs-on: windows-latest
    env:
      KEY_VAULT_NAME: 'new-test-marv'

    steps:
    - name: Check out repository
      uses: actions/checkout@v3.0.2

    - name: 'Az CLI login using OIDC'
      uses: azure/login@v1
      with:
        client-id: ${{ fe580c76-4014-4070-aa32-fa16ec1b4fd1 }}
        tenant-id: ${{ d4d433d3-ddf4-483c-b9fe-04c1bcd03df6 }}
        subscription-id: ${{ e1671b17-35f5-4275-a190-cea038e7ba43 }}
        enable-AzPSSession: true

    - name: Rotate VMs administrator passwords
      uses: Pwd9000-ML/azure-vm-password-rotate@v1.1.0
      with:
        key-vault-name: ${{ env.KEY_VAULT_NAME }}